name: Payload React

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: install
        run: npm i
      - name: ESLint
        run: npx eslint src --ext .js
      - name: Prettier
        run: npx prettier -c 'src/**/*.js'
      - name: Tests
        run: npm t
